### ISSUE TITLE
Grammar errors in draft 2020-01

### ISSUE THREAD

**Issue by smithdtyler** [saeaadl/aadlv3#18]
On page 6, section 3.6

- [ ] "(6)	An interface extension of multiple interfaces combines all elements of the interfaces become part of the resulting composite interface. "

This is confusing, I think the word "become" is incorrect. 

On page 8, 4.3.1:

- [ ] •	subcomponents that represent instances of **component** inside a given component. Subcomponents may themselves contain subcomponents leading to a component hierarchy,

On page 11, comment 

- [ ] // An actuator functional interface specifies input for another component which  // **result** in effects on a physical component through the feature.

On page 13, "implantations" is probably supposed to be "implementation." 

- [ ] ...but cannot change the topology by replacing **implantations** specified for subcomponents, or by adding subcomponents or connections. 

On page 28, I think the bolded word "of" should be "in":

- [ ] (2)	A state variable represents the current state **of** a given set of states. The set of states is represented by a set of literals in an enumeration type.

**Comment by reteprelief** [comment]
fixed
