### ISSUE TITLE
Confusing reference to state variable in section 12: Modes

### ISSUE THREAD

**Issue by smithdtyler** [saeaadl/aadlv3#20]
The concept of a state variable is introduced in section 11 with reference to behavior specification, then is used again in describing modes. This is confusing. Are modes being merged with state specification? If so, why are both "mode" and "state" used? 

(4)	A **state variable** represents a mode, which reflects dynamic behavior of an architecture in terms of its topology. In different modes different subsets of subcomponents and connections can be active. The architecture can be a platform architecture with hardware and physical components, or a task and communication architecture representing embedded software.

**Comment by reteprelief** [comment]
Cleaned up.
